<?php return array (
  'id' => 43,
  'title' => '用户组管理',
  'sorted' => 0,
  'id_prefix' => 'user_group_',
  'pid' => 40,
  'middleware' => '1,2',
  'model' => '2',
  'function_type' => '1',
  'url' => 'user/user_group/index',
  'method' => 'UserGroupController@index',
  'inheritance' => NULL,
  'inheritance_note' => NULL,
  'main_table' => 'blk_user_group',
  'associated_type' => NULL,
  'associated_table' => NULL,
  'external_field' => NULL,
  'datatable_set' => 
  array (
    'id' => 
    array (
      'field_type' => 'int',
      'field_length' => '11',
      'sorting' => NULL,
      'fixed' => '0',
      'title' => NULL,
      'field' => 'id',
      'field_from' => 'main_table',
      'width' => NULL,
      'search' => '0',
      'attribute' => NULL,
    ),
    'rules' => 
    array (
      'field_type' => 'text',
      'field_length' => 'no_limit',
      'sorting' => NULL,
      'fixed' => '0',
      'title' => '权限规则',
      'field' => 'rules',
      'field_from' => 'main_table',
      'width' => NULL,
      'search' => '0',
      'attribute' => NULL,
    ),
    'name' => 
    array (
      'field_type' => 'varchar',
      'field_length' => '50',
      'sorting' => '1',
      'fixed' => 'left',
      'title' => '用户组',
      'field' => 'name',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => '0',
      'attribute' => NULL,
    ),
    'note' => 
    array (
      'field_type' => 'varchar',
      'field_length' => '250',
      'sorting' => '2',
      'fixed' => '0',
      'title' => '备注',
      'field' => 'note',
      'field_from' => 'main_table',
      'width' => '400',
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => '0',
      'attribute' => NULL,
    ),
    'created_at' => 
    array (
      'field_type' => 'datetime',
      'field_length' => 'no_limit',
      'sorting' => '999',
      'fixed' => '0',
      'title' => '创建时间',
      'field' => 'created_at',
      'field_from' => 'main_table',
      'width' => NULL,
      'read' => 'on',
      'search' => '0',
      'attribute' => NULL,
    ),
    'updated_at' => 
    array (
      'field_type' => 'datetime',
      'field_length' => 'no_limit',
      'sorting' => '999',
      'fixed' => '0',
      'title' => '修改时间',
      'field' => 'updated_at',
      'field_from' => 'main_table',
      'width' => NULL,
      'read' => 'on',
      'search' => '0',
      'attribute' => NULL,
    ),
    'deleted_at' => 
    array (
      'field_type' => 'datetime',
      'field_length' => 'no_limit',
      'sorting' => '999',
      'fixed' => '0',
      'title' => '删除时间',
      'field' => 'deleted_at',
      'field_from' => 'main_table',
      'width' => NULL,
      'read' => 'on',
      'search' => '0',
      'attribute' => NULL,
    ),
  ),
  'head_menu' => 
  array (
    'search' => 
    array (
      'text' => '搜索',
      'icon' => 'layui-icon-search',
      'must' => 'on',
      'width' => '800px',
      'height' => '90%',
      'method' => NULL,
    ),
    'create' => 
    array (
      'text' => '新增',
      'icon' => 'layui-icon-add-1',
      'must' => 'on',
      'width' => '100%',
      'height' => '100%',
      'method' => NULL,
    ),
    'update' => 
    array (
      'text' => '修改',
      'icon' => 'layui-icon-edit',
      'must' => 'on',
      'width' => '100%',
      'height' => '100%',
      'method' => NULL,
    ),
    'delete' => 
    array (
      'text' => '删除',
      'icon' => 'layui-icon-delete',
      'must' => 'on',
      'width' => NULL,
      'height' => NULL,
      'method' => NULL,
    ),
    'recycle' => 
    array (
      'text' => '回收站',
      'icon' => 'layui-icon-fonts-del',
      'must' => 'on',
      'width' => '100%',
      'height' => '100%',
      'method' => NULL,
    ),
    'recovery' => 
    array (
      'text' => '数据恢复',
      'icon' => 'layui-icon-prev',
      'must' => 'on',
      'width' => NULL,
      'height' => NULL,
      'method' => NULL,
    ),
  ),
  'other_set' => 
  array (
    'limit' => '20',
    'cell_min_width' => '160',
    'line_button_area_width' => '160',
  ),
  'route' => 
  array (
    'route_path' => 'user/user_group/',
    'route_name' => 'index',
    'controller' => 'App\\Http\\Controllers\\User\\UserGroupController',
    'method' => 'index',
  ),
  'new_head_menu' => NULL,
  'line_button' => 
  array (
    'permissions' => 
    array (
      'text' => '用户组授权',
      'style' => 'layui-btn-normal',
      'open_tepe' => 'window',
      'must' => 'on',
      'width' => '100%',
      'height' => '100%',
      'method' => 'permissions',
    ),
    'display' => 
    array (
      'text' => '查看',
      'style' => 'layui-btn-warm',
      'open_tepe' => 'window',
      'must' => 'on',
      'width' => '100%',
      'height' => '100%',
      'method' => 'display',
    ),
  ),
);?>