<?php return array (
  'id' => 81,
  'title' => '中间件管理',
  'sorted' => 0,
  'id_prefix' => 'middleware_',
  'pid' => 45,
  'middleware' => '',
  'model' => '2',
  'function_type' => '2',
  'url' => 'lazykit/system/middleware_management',
  'method' => 'SystemController@middlewareManagement',
  'inheritance' => NULL,
  'inheritance_note' => NULL,
  'main_table' => 'blk_middleware',
  'associated_type' => NULL,
  'associated_table' => NULL,
  'external_field' => NULL,
  'datatable_set' => 
  array (
    'id' => 
    array (
      'field_type' => 'int',
      'field_length' => '11',
      'sorting' => NULL,
      'fixed' => '0',
      'title' => NULL,
      'field' => 'id',
      'field_from' => 'main_table',
      'width' => NULL,
      'search' => '0',
      'attribute' => NULL,
    ),
    'key' => 
    array (
      'field_type' => 'varchar',
      'field_length' => '50',
      'sorting' => NULL,
      'fixed' => '0',
      'title' => '中间件键名',
      'field' => 'key',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => '0',
      'attribute' => NULL,
    ),
    'name' => 
    array (
      'field_type' => 'varchar',
      'field_length' => '50',
      'sorting' => NULL,
      'fixed' => '0',
      'title' => '中间键名称',
      'field' => 'name',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => '0',
      'attribute' => NULL,
    ),
    'note' => 
    array (
      'field_type' => 'text',
      'field_length' => 'no_limit',
      'sorting' => NULL,
      'fixed' => '0',
      'title' => '使用说明',
      'field' => 'note',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => '0',
      'attribute' => NULL,
    ),
    'deleted_at' => 
    array (
      'field_type' => 'datetime',
      'field_length' => 'no_limit',
      'sorting' => NULL,
      'fixed' => '0',
      'title' => '删除时间',
      'field' => 'deleted_at',
      'field_from' => 'main_table',
      'width' => NULL,
      'read' => 'on',
      'search' => '0',
      'attribute' => NULL,
    ),
  ),
  'head_menu' => 
  array (
    'search' => 
    array (
      'text' => '搜索',
      'icon' => 'layui-icon-search',
      'width' => '800px',
      'height' => '90%',
      'method' => NULL,
    ),
    'create' => 
    array (
      'text' => '新增',
      'icon' => 'layui-icon-add-1',
      'must' => 'on',
      'width' => '100%',
      'height' => '100%',
      'method' => NULL,
    ),
    'update' => 
    array (
      'text' => '修改',
      'icon' => 'layui-icon-edit',
      'must' => 'on',
      'width' => '100%',
      'height' => '100%',
      'method' => NULL,
    ),
    'delete' => 
    array (
      'text' => '删除',
      'icon' => 'layui-icon-delete',
      'must' => 'on',
      'width' => NULL,
      'height' => NULL,
      'method' => NULL,
    ),
  ),
  'other_set' => 
  array (
    'limit' => '20',
    'cell_min_width' => '160',
    'line_button_area_width' => '160',
  ),
  'route' => 
  array (
    'route_path' => 'lazykit/system/',
    'route_name' => 'middleware_management',
    'controller' => 'App\\Http\\Controllers\\Lazykit\\SystemController',
    'method' => 'middlewareManagement',
  ),
  'new_head_menu' => NULL,
  'line_button' => NULL,
);?>