<?php return array (
  'id' => 15,
  'title' => 'Datatable完整演示',
  'pid' => 31,
  'model' => 'datatable',
  'url' => '/lazykit/demo',
  'method' => 'DemoController@index',
  'module_id' => '1',
  'main_table' => 'tools_demo',
  'associated_type' => '',
  'associated_table' => '',
  'external_field' => '',
  'datatable_set' => 
  array (
    'id' => 
    array (
      'sorting' => '0',
      'fixed' => NULL,
      'title' => '编号',
      'field' => 'id',
      'field_from' => 'main_table',
      'width' => NULL,
      'export' => 'on',
    ),
    'the_title' => 
    array (
      'sorting' => '1',
      'fixed' => 'left',
      'title' => '标题',
      'field' => 'the_title',
      'field_from' => 'main_table',
      'width' => '300',
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
      'import' => 'on',
      'export' => 'on',
    ),
    'text' => 
    array (
      'sorting' => '2',
      'fixed' => NULL,
      'title' => '文本',
      'field' => 'text',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
      'import' => 'on',
      'export' => 'on',
    ),
    'textarea' => 
    array (
      'sorting' => '3',
      'fixed' => NULL,
      'title' => '文本区域',
      'field' => 'textarea',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'import' => 'on',
    ),
    'select' => 
    array (
      'sorting' => '8',
      'fixed' => NULL,
      'title' => '下拉选择',
      'field' => 'select',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
      'import' => 'on',
    ),
    'tree_select' => 
    array (
      'sorting' => '9',
      'fixed' => NULL,
      'title' => '树型下拉选择',
      'field' => 'tree_select',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
      'import' => 'on',
    ),
    'table_select' => 
    array (
      'sorting' => '10',
      'fixed' => NULL,
      'title' => '表格选择',
      'field' => 'table_select',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
    ),
    'multiple_select' => 
    array (
      'sorting' => '11',
      'fixed' => NULL,
      'title' => '下拉多选',
      'field' => 'multiple_select',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
    ),
    'cascade_select' => 
    array (
      'sorting' => '12',
      'fixed' => NULL,
      'title' => '级联选择',
      'field' => 'cascade_select',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
    ),
    'single_photo_upload' => 
    array (
      'sorting' => '40',
      'fixed' => NULL,
      'title' => '单图上传',
      'field' => 'single_photo_upload',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'photos_upload' => 
    array (
      'sorting' => '41',
      'fixed' => NULL,
      'title' => '多图上传',
      'field' => 'photos_upload',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'single_file_upload' => 
    array (
      'sorting' => '42',
      'fixed' => NULL,
      'title' => '单文件上传',
      'field' => 'single_file_upload',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'files_upload' => 
    array (
      'sorting' => '43',
      'fixed' => NULL,
      'title' => '多文件上传',
      'field' => 'files_upload',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'year' => 
    array (
      'sorting' => '60',
      'fixed' => NULL,
      'title' => '年选择器',
      'field' => 'year',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'year_mouth' => 
    array (
      'sorting' => '61',
      'fixed' => NULL,
      'title' => '年月选择器',
      'field' => 'year_mouth',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'date' => 
    array (
      'sorting' => '62',
      'fixed' => NULL,
      'title' => '日期选择器',
      'field' => 'date',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'time' => 
    array (
      'sorting' => '63',
      'fixed' => NULL,
      'title' => '时间选择器',
      'field' => 'time',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'datetime' => 
    array (
      'sorting' => '64',
      'fixed' => NULL,
      'title' => '日期时间选择器',
      'field' => 'datetime',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
    ),
    'year_scope' => 
    array (
      'sorting' => '65',
      'fixed' => NULL,
      'title' => '年范围',
      'field' => 'year_scope',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
    ),
    'year_mouth_scope' => 
    array (
      'sorting' => '66',
      'fixed' => NULL,
      'title' => '年月范围',
      'field' => 'year_mouth_scope',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
    ),
    'date_scope' => 
    array (
      'sorting' => '67',
      'fixed' => NULL,
      'title' => '日期范围',
      'field' => 'date_scope',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
    ),
    'time_scope' => 
    array (
      'sorting' => '68',
      'fixed' => NULL,
      'title' => '时间范围',
      'field' => 'time_scope',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
    ),
    'datetime_scope' => 
    array (
      'sorting' => '69',
      'fixed' => NULL,
      'title' => '日期时间范围',
      'field' => 'datetime_scope',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
    ),
    'color_choices' => 
    array (
      'sorting' => '80',
      'fixed' => NULL,
      'title' => '颜色选择',
      'field' => 'color_choices',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
      'search' => 'on',
    ),
    'editormd' => 
    array (
      'sorting' => '130',
      'fixed' => NULL,
      'title' => 'Markdown 编辑器',
      'field' => 'editormd',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'layui_editer' => 
    array (
      'sorting' => '131',
      'fixed' => NULL,
      'title' => 'layui 编辑器',
      'field' => 'layui_editer',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'layui_editer_simple' => 
    array (
      'sorting' => '132',
      'fixed' => NULL,
      'title' => 'layui 编辑器精简版',
      'field' => 'layui_editer_simple',
      'field_from' => 'main_table',
      'width' => NULL,
      'create' => 'on',
      'update' => 'on',
      'read' => 'on',
    ),
    'created_at' => 
    array (
      'sorting' => '999',
      'fixed' => NULL,
      'title' => '创建时间',
      'field' => 'created_at',
      'field_from' => 'main_table',
      'width' => NULL,
    ),
    'updated_at' => 
    array (
      'sorting' => '999',
      'fixed' => NULL,
      'title' => '修改时间',
      'field' => 'updated_at',
      'field_from' => 'main_table',
      'width' => NULL,
      'read' => 'on',
    ),
    'deleted_at' => 
    array (
      'sorting' => '999',
      'fixed' => NULL,
      'title' => '删除时间',
      'field' => 'deleted_at',
      'field_from' => 'main_table',
      'width' => NULL,
      'read' => 'on',
    ),
  ),
  'head_menu' => 
  array (
    'search' => 
    array (
      'text' => '搜索',
      'icon' => 'layui-icon-search',
      'must' => 'on',
      'width' => '90%',
      'height' => '90%',
      'method' => NULL,
    ),
    'create' => 
    array (
      'text' => '新增',
      'icon' => 'layui-icon-add-1',
      'must' => 'on',
      'width' => '100%',
      'height' => '100%',
      'method' => NULL,
    ),
    'update' => 
    array (
      'text' => '修改',
      'icon' => 'layui-icon-edit',
      'must' => 'on',
      'width' => '100%',
      'height' => '100%',
      'method' => NULL,
    ),
    'delete' => 
    array (
      'text' => '删除',
      'icon' => 'layui-icon-delete',
      'must' => 'on',
      'width' => NULL,
      'height' => NULL,
      'method' => NULL,
    ),
    'recycle' => 
    array (
      'text' => '回收站',
      'icon' => 'layui-icon-delete',
      'must' => 'on',
      'width' => '100%',
      'height' => '100%',
      'method' => NULL,
    ),
    'recovery' => 
    array (
      'text' => '数据恢复',
      'icon' => 'layui-icon-delete',
      'must' => 'on',
      'width' => NULL,
      'height' => NULL,
      'method' => NULL,
    ),
  ),
  'other_set' => 
  array (
    'limit' => '30',
    'cell_min_width' => '160',
    'line_button_area_width' => '160',
  ),
  'route' => 
  array (
    'route_path' => '/lazykit/demo/',
    'route_name' => 'index',
    'controller' => 'App\\Http\\Controllers\\Lazykit\\DemoController',
    'method' => 'index',
  ),
  'new_head_menu' => NULL,
  'line_button' => NULL,
);?>